version: "3.9"
services:
   webapp:
      build: webapp/
      ports:
         - "80"
         - "443"
      volumes:
         - type: bind
           source: ../public/
           target: /var/www/html
         - type: volume
           source: webapp-etc
           target: /etc
      restart: unless-stopped
      networks:
         - frontend
         - backend
      depends_on:
         - database
   database:
      build: database/
      volumes:
         - db-store:/var/lib/postgresql/data
      environment:
         - POSTGRES_PASSWORD=passw0rd
         - POSTGRES_DB=webapp
      restart: unless-stopped
      networks:
         - backend
   phpPgAdmin:
      image: dpage/pgadmin4:latest
      ports:
         - "80"
         - "443"
      environment:
         - PGADMIN_DEFAULT_EMAIL=phppgadmin@n138.jp
         - PGADMIN_DEFAULT_PASSWORD=phppgadmin
      restart: unless-stopped
      volumes:
         - pgadmin:/var/lib/pgadmin
      networks:
         - frontend
         - backend
      depends_on:
         - database
volumes:
   db-store:
   pgadmin:
   webapp-etc:
networks:
   frontend:
      external: true
   backend:
