name: Docker Image CI (name=moji-okoshi-v2, path=/moji-okoshi/moji-okoshi-client2-share/docker/database) 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image path=/moji-okoshi/moji-okoshi-client2-share/docker/database
      run: docker build . --file ./moji-okoshi/moji-okoshi-client2-share/docker/database/Dockerfile --tag my-image-name:$(date +%s)
